[platformio]
src_dir = src

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
board_build.partitions = partitions_s3.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
build_flags = 
    -I runtime/custom_c
    -D BOARD_HAS_PSRAM
    -O3
