[platformio]
src_dir = esp32/main

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
board_build.partitions = esp32/partitions.csv
build_flags = 
    -I runtime/custom_c
    -I esp32/main
